from typing import Optional

class tzinfo:
    def utcoffset(self, dt: Optional['datetime']) -> Optional['timedelta']: ...
    def dst(self, dt: Optional['datetime']) -> Optional['timedelta']: ...
    def tzname(self, dt: Optional['datetime']) -> Optional[str]: ...

class timezone(tzinfo):
    utc: 'timezone'
    def __init__(self, offset: 'timedelta', name: Optional[str] = ...) -> None: ...

